-- payOS Boost orders. The public Boost button stays disabled until a real
-- payment has been confirmed end-to-end. No seller/anon SQL path can grant it.

create table if not exists public.boost_orders (
  order_code bigint generated by default as identity (start with 260924000000) primary key,
  listing_id uuid not null references public.rental_listings(id),
  seller_id uuid not null references auth.users(id),
  days integer not null check (days > 0 and days <= 365),
  amount integer not null check (amount > 0),
  status text not null default 'PENDING'
    check (status in ('PENDING', 'LINKED', 'PAID', 'NEEDS_REVIEW')),
  payment_link_id text unique,
  checkout_url text,
  payos_reference text unique,
  payment_id uuid unique references public.payments(id),
  paid_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_boost_orders_seller_created
  on public.boost_orders (seller_id, created_at desc);
create index if not exists idx_boost_orders_listing_status
  on public.boost_orders (listing_id, status);

-- Old boost dates may come from the previously unpaid demo flow. Only this
-- server-set flag, written with a verified PAID order, enables marketplace rank.
alter table public.rental_listings
  add column if not exists boost_payment_verified boolean not null default false;

create or replace function public.guard_boost_payment_verified()
returns trigger
language plpgsql security definer set search_path = public as $$
declare
  v_allowed boolean := coalesce(current_setting('app.allow_boost_write', true), '') = 'on';
begin
  if tg_op = 'INSERT' then
    if new.boost_payment_verified and not v_allowed then
      raise exception 'BOOST_REQUIRES_VERIFIED_PAYMENT';
    end if;
  elsif new.boost_payment_verified is distinct from old.boost_payment_verified and not v_allowed then
    raise exception 'BOOST_REQUIRES_VERIFIED_PAYMENT';
  end if;
  return new;
end $$;

drop trigger if exists trg_guard_boost_payment_verified_insert on public.rental_listings;
create trigger trg_guard_boost_payment_verified_insert
  before insert on public.rental_listings
  for each row execute function public.guard_boost_payment_verified();
drop trigger if exists trg_guard_boost_payment_verified_update on public.rental_listings;
create trigger trg_guard_boost_payment_verified_update
  before update of boost_payment_verified on public.rental_listings
  for each row execute function public.guard_boost_payment_verified();
revoke all on function public.guard_boost_payment_verified() from public, anon, authenticated;

alter table public.boost_orders enable row level security;
drop policy if exists "Seller reads own boost orders" on public.boost_orders;
create policy "Seller reads own boost orders" on public.boost_orders
  for select to authenticated using (seller_id = auth.uid());
revoke all on public.boost_orders from public, anon, authenticated;
grant select on public.boost_orders to authenticated;

-- Called only by the checkout Edge Function after it has verified the user's
-- JWT. The client cannot provide price or status, and cannot invoke this RPC.
create or replace function public.begin_boost_checkout(
  p_seller_id uuid,
  p_listing_id uuid,
  p_days integer
) returns table (order_code bigint, amount integer)
language plpgsql volatile security definer set search_path = public as $$
declare
  v_config jsonb;
  v_index integer;
  v_amount numeric;
begin
  if auth.role() is distinct from 'service_role' then
    raise exception 'FORBIDDEN' using errcode = '42501';
  end if;
  if p_seller_id is null or p_listing_id is null or p_days is null then
    raise exception 'INVALID_BOOST_PACKAGE' using errcode = '23514';
  end if;
  if not exists (
    select 1 from public.rental_listings
    where id = p_listing_id and seller_id = p_seller_id
      and status = 'Active' and deleted_at is null
  ) then
    raise exception 'LISTING_NOT_CONTACTABLE' using errcode = '23514';
  end if;

  select value into v_config from public.platform_settings
  where key = 'boost_config';
  if v_config is null then
    raise exception 'BOOST_CONFIG_MISSING' using errcode = '23514';
  end if;
  select ordinality - 1 into v_index
  from jsonb_array_elements(v_config -> 'days') with ordinality as d(value, ordinality)
  where (d.value)::integer = p_days limit 1;
  if v_index is null then
    raise exception 'INVALID_BOOST_PACKAGE' using errcode = '23514';
  end if;
  v_amount := ((v_config -> 'price') -> v_index)::numeric;
  if v_amount is null or v_amount <= 0 or v_amount > 1000000000
      or v_amount <> trunc(v_amount) then
    raise exception 'BOOST_CONFIG_MISSING' using errcode = '23514';
  end if;

  return query
    insert into public.boost_orders (listing_id, seller_id, days, amount)
    values (p_listing_id, p_seller_id, p_days, v_amount::integer)
    returning boost_orders.order_code, boost_orders.amount;
end $$;

-- Save the checkout link only after the payOS API confirms its order code and
-- amount. The URL is stored for reconciliation, not used to prove payment.
create or replace function public.attach_boost_checkout_link(
  p_order_code bigint,
  p_payment_link_id text,
  p_checkout_url text
) returns void
language plpgsql volatile security definer set search_path = public as $$
begin
  if auth.role() is distinct from 'service_role' then
    raise exception 'FORBIDDEN' using errcode = '42501';
  end if;
  if nullif(btrim(p_payment_link_id), '') is null
      or p_checkout_url not like 'https://pay.payos.vn/%' then
    raise exception 'INVALID_PAYMENT_LINK' using errcode = '23514';
  end if;
  -- A signed webhook can arrive before this RPC finishes. Never move a paid
  -- order back to LINKED; just attach the same link for reconciliation.
  update public.boost_orders
  set payment_link_id = p_payment_link_id,
      checkout_url = p_checkout_url,
      status = case when status = 'PENDING' then 'LINKED' else status end,
      updated_at = now()
  where order_code = p_order_code
    and status in ('PENDING', 'LINKED', 'PAID', 'NEEDS_REVIEW')
    and (payment_link_id is null or payment_link_id = p_payment_link_id);
  if not found then
    raise exception 'BOOST_ORDER_LINK_MISMATCH' using errcode = '23514';
  end if;
end $$;

-- Called only by the webhook Edge Function AFTER payOS signature verification.
-- Row locks and status make duplicate webhook delivery idempotent. Recording
-- the payment and extending the listing are one database transaction.
create or replace function public.complete_verified_boost_payment(
  p_order_code bigint,
  p_amount integer,
  p_payment_link_id text,
  p_reference text
) returns text
language plpgsql volatile security definer set search_path = public as $$
declare
  v_order public.boost_orders;
  v_listing public.rental_listings;
  v_listing_exists boolean;
  v_payment_id uuid;
begin
  if auth.role() is distinct from 'service_role' then
    raise exception 'FORBIDDEN' using errcode = '42501';
  end if;
  select * into v_order from public.boost_orders
  where order_code = p_order_code for update;
  if not found then
    return 'UNKNOWN_ORDER'; -- payOS sends a signed sample to verify webhook URL.
  end if;
  if p_amount is distinct from v_order.amount
      or nullif(btrim(p_payment_link_id), '') is null
      or nullif(btrim(p_reference), '') is null
      or (v_order.payment_link_id is not null
          and p_payment_link_id <> v_order.payment_link_id) then
    raise exception 'BOOST_PAYMENT_MISMATCH' using errcode = '23514';
  end if;
  if v_order.status in ('PAID', 'NEEDS_REVIEW') then
    if v_order.payos_reference is distinct from p_reference then
      raise exception 'BOOST_PAYMENT_REPLAY_MISMATCH' using errcode = '23514';
    end if;
    return v_order.status;
  end if;

  select * into v_listing from public.rental_listings
  where id = v_order.listing_id for update;
  v_listing_exists := found;
  insert into public.payments (invoice_id, owner_id, amount, method, paid_at, purpose)
  values (null, v_order.seller_id, v_order.amount, 'BankTransfer', now(), 'Boost')
  returning id into v_payment_id;

  if not v_listing_exists or v_listing.status <> 'Active' or v_listing.deleted_at is not null then
    update public.boost_orders
    set status = 'NEEDS_REVIEW', payment_link_id = coalesce(payment_link_id, p_payment_link_id),
        payos_reference = nullif(p_reference, ''), payment_id = v_payment_id,
        paid_at = now(), updated_at = now()
    where order_code = p_order_code;
    return 'NEEDS_REVIEW';
  end if;

  perform set_config('app.allow_boost_write', 'on', true);
  update public.rental_listings
  set boost_expire_at = greatest(coalesce(boost_expire_at, now()), now())
      + make_interval(days => v_order.days),
      boost_payment_verified = true
  where id = v_order.listing_id;
  perform set_config('app.allow_boost_write', 'off', true);

  update public.boost_orders
  set status = 'PAID', payment_link_id = coalesce(payment_link_id, p_payment_link_id),
      payos_reference = nullif(p_reference, ''), payment_id = v_payment_id,
      paid_at = now(), updated_at = now()
  where order_code = p_order_code;
  return 'PAID';
end $$;

revoke execute on function public.begin_boost_checkout(uuid, uuid, integer)
  from public, anon, authenticated;
revoke execute on function public.attach_boost_checkout_link(bigint, text, text)
  from public, anon, authenticated;
revoke execute on function public.complete_verified_boost_payment(bigint, integer, text, text)
  from public, anon, authenticated;
grant execute on function public.begin_boost_checkout(uuid, uuid, integer) to service_role;
grant execute on function public.attach_boost_checkout_link(bigint, text, text) to service_role;
grant execute on function public.complete_verified_boost_payment(bigint, integer, text, text) to service_role;
